---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: kube-monkey
    labels:
        apps: kube-monkey
  spec:
    replicas: 1
    selector:
        matchLabels:
            app: kube-monkey
    template:
      metadata:
        labels:
          app: kube-monkey
      spec:
        containers:
          - name: kube-monkey
            command:
              - "/kube-monkey"
            args: ["-v=5", "-log_dir=/var/log/kube-monkey"]
            image: localhost:5000/kube-monkey:myv1.0.0
            volumeMounts:
              - name: config-volume
                mountPath: "/etc/kube-monkey"
        volumes:
          - name: config-volume
            configMap:
              name: kube-monkey-config-map
